# Form implementation generated from reading ui file 'imageGui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PictureWindow(object):
    def setupUi(self, PictureWindow):
        PictureWindow.setObjectName("PictureWindow")
        PictureWindow.resize(480, 290)
        PictureWindow.setMinimumSize(QtCore.QSize(480, 290))
        PictureWindow.setStyleSheet("image: url(space.png);") # Replace "space.png" with the path to your image file

        self.retranslateUi(PictureWindow)
        QtCore.QMetaObject.connectSlotsByName(PictureWindow)

    def retranslateUi(self, PictureWindow):
        _translate = QtCore.QCoreApplication.translate
        PictureWindow.setWindowTitle(_translate("PictureWindow", "Picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PictureWindow = QtWidgets.QWidget()
    ui = Ui_PictureWindow()
    ui.setupUi(PictureWindow)
    PictureWindow.show()
    sys.exit(app.exec())
